"""Argus Fleet execution-plane primitives."""

from .enrollment import (
    BOOTSTRAP_DIGEST_PROFILE,
    FLEET_REGISTRY_VERSION,
    BootstrapCredential,
    EnrollmentAcknowledgement,
    EnrollmentConflict,
    EnrollmentRequest,
    EnrollmentResult,
    FleetEnrollmentError,
    FleetEnrollmentRegistry,
)

from .heartbeat import (
    CLOCK_ASSESSMENT_VERSION,
    FLEET_HEARTBEAT_VERSION,
    CapacityAdvertisement,
    ClockAssessment,
    ClockProbeChallenge,
    ClockProbeResponse,
    FleetHeartbeatError,
    FleetHeartbeatRegistry,
    HeartbeatConflict,
    HeartbeatReceipt,
    ImageAdvertisement,
    NodeHealth,
    NodeHeartbeat,
)

from .identity import (
    FLEET_IDENTITY_VERSION,
    PRIVATE_KEY_FILE_VERSION,
    FleetIdentityError,
    NodeKeyPair,
    canonical_signed_message,
    public_key_fingerprint,
    verify_signature,
)

__all__ = [
    "NodeHeartbeat",
    "NodeHealth",
    "ImageAdvertisement",
    "HeartbeatReceipt",
    "HeartbeatConflict",
    "FleetHeartbeatRegistry",
    "FleetHeartbeatError",
    "ClockProbeResponse",
    "ClockProbeChallenge",
    "ClockAssessment",
    "CapacityAdvertisement",
    "FLEET_HEARTBEAT_VERSION",
    "CLOCK_ASSESSMENT_VERSION",
    "BOOTSTRAP_DIGEST_PROFILE",
    "FLEET_IDENTITY_VERSION",
    "FLEET_REGISTRY_VERSION",
    "PRIVATE_KEY_FILE_VERSION",
    "BootstrapCredential",
    "EnrollmentAcknowledgement",
    "EnrollmentConflict",
    "EnrollmentRequest",
    "EnrollmentResult",
    "FleetEnrollmentError",
    "FleetEnrollmentRegistry",
    "FleetIdentityError",
    "NodeKeyPair",
    "canonical_signed_message",
    "public_key_fingerprint",
    "verify_signature",
]
