import json
from collections import UserDict

import pytest

from argus.ates import (
    AtesEventStore,
    EvidenceContext,
    EvidenceDisposition,
    EvidencePrivacyConfig,
    EvidencePrivacyPolicy,
    EventType,
    PrivacyPolicyError,
    RunId,
    to_json_compatible,
)
from argus.engine.runner import run_test
from argus.engine.spec import parse_spec
from tests.conftest import FakeAdapter, FakeProvider


def _events(project_dir, run_id):
    with AtesEventStore(project_dir, RunId(run_id)) as store:
        return tuple(store.events)


class _MutatingSink:
    def __init__(self):
        self.calls = []
        self.refs = []

    def put(self, value, *, context, field_name, protected_ref):
        self.calls.append((value, context, field_name))
        self.refs.append(protected_ref)
        if isinstance(value, dict):
            value.clear()
        # A hostile/legacy sink may still return payload-derived text. The
        # policy must ignore it because canonical refs are generated by Argus.
        return "protected://vault/1234"


def test_mutating_sink_cannot_change_classification_or_canonical_reference():
    original = {"pin": "1234"}
    sink = _MutatingSink()
    policy = EvidencePrivacyPolicy(
        EvidencePrivacyConfig(
            protected_contexts=frozenset({EvidenceContext.OPERATOR_ANNOTATION})
        ),
        protected_sink=sink,
    )

    projected = policy.capture(
        original,
        context=EvidenceContext.OPERATOR_ANNOTATION,
    )

    assert original == {"pin": "1234"}
    assert sink.calls[0][0] == {}
    assert projected.disposition is EvidenceDisposition.PROTECTED_REF
    assert projected.protected_ref == sink.refs[0]
    assert projected.protected_ref.startswith("protected://ates/")
    assert projected.protected_ref != "protected://vault/1234"
    assert "1234" not in projected.protected_ref


def test_policy_generated_refs_replace_short_secret_randomness_heuristics(monkeypatch):
    # Even if a generated token happens to contain a short protected value, its
    # provenance is known: Argus generated it independently before persistence.
    monkeypatch.setattr(
        "argus.ates.privacy.secrets.token_hex",
        lambda _size: "a" * 31 + "1",
    )
    policy = EvidencePrivacyPolicy.standard()
    issued = policy.issue_secret_ref()

    projected = policy.capture(
        1,
        context=EvidenceContext.ACTION_PARAMETER,
        secret_refs=(issued,),
    )
    assert projected.disposition is EvidenceDisposition.REDACTED
    assert projected.secret_refs == (issued,)

    with pytest.raises(PrivacyPolicyError, match="policy-issued opaque references"):
        policy.capture(
            1,
            context=EvidenceContext.ACTION_PARAMETER,
            secret_refs=("secret://ates/11111111111111111111111111111111",),
        )


def test_secret_ref_path_accepts_generic_mapping_after_safe_snapshot():
    policy = EvidencePrivacyPolicy.standard()
    issued = policy.issue_secret_ref()
    value = UserDict({"pin": "123"})

    projected = policy.capture(
        value,
        context=EvidenceContext.ACTION_PARAMETER,
        secret_refs=(issued,),
    )

    assert projected.disposition is EvidenceDisposition.REDACTED
    assert projected.secret_refs == (issued,)
    assert value == {"pin": "123"}


class _RetrySink:
    def __init__(self):
        self.calls = []
        self.refs = []

    def put(self, value, *, context, field_name, protected_ref):
        self.calls.append((value, context, field_name))
        self.refs.append(protected_ref)


def test_protected_retry_uses_real_failure_once_and_reuses_reference(tmp_path):
    failure_note = "private retry cause from first attempt"
    sink = _RetrySink()
    policy = EvidencePrivacyPolicy(
        EvidencePrivacyConfig(
            protected_contexts=frozenset({EvidenceContext.RETRY_REASON})
        ),
        protected_sink=sink,
    )
    spec = parse_spec(
        """\
name: protected retry reason
target: {adapter: desktop-gui, launch: fake.exe}
retries: 1
steps:
  - "Complete the operation"
"""
    )
    provider = FakeProvider(
        [
            json.dumps({"action": "done", "success": False, "note": failure_note}),
            json.dumps({"action": "done", "success": True, "note": "recovered"}),
        ]
    )

    result = run_test(
        spec,
        provider,
        FakeAdapter(),
        project_dir=tmp_path,
        privacy_policy=policy,
    )

    assert result.status == "pass"
    assert result.steps[0].flaky is True
    assert sink.calls == [(failure_note, EvidenceContext.RETRY_REASON, "reason")]
    assert len(sink.refs) == 1

    events = _events(tmp_path, result.ates_run_id)
    scheduled = next(
        to_json_compatible(event.payload)
        for event in events
        if event.envelope.event_type is EventType.STEP_RETRY_SCHEDULED
    )
    starts = [
        to_json_compatible(event.payload)["attempt"]
        for event in events
        if event.envelope.event_type is EventType.STEP_ATTEMPT_STARTED
    ]

    assert len(starts) == 2
    scheduled_reason = scheduled["reason"]
    next_attempt_reason = starts[1]["retry_reason"]
    assert scheduled_reason["disposition"] == "protected_ref"
    assert next_attempt_reason["disposition"] == "protected_ref"
    assert scheduled_reason["protected_ref"] == sink.refs[0]
    assert next_attempt_reason["protected_ref"] == sink.refs[0]

    persisted = b"".join(event.canonical_line() for event in events)
    assert failure_note.encode() not in persisted
